version: 2
jobs:
  build:
    working_directory: ~/Python-maze-gen
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout: master
      - run:
          name: Running tests
          command: python mazeTests.py